# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a552f25396b528c96260b3ee060ac014e3901c748ab95e7b48a5121669d5df6ce76338d2078191d9b5f310b17cf675cfa3f10c7914bc68402b4430dd9a20f39b

test:
  secret_key_base: 6cc94980649e3e50bcee01098864df7d9f5ec71e54c093a7d6932707ad829b8dfcf540907af35985507893312cf1f6d2d83a4309a4866a0b67bb2a2eb66f18b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
